version: '2'
services:
  nginx:
    image: nginx
    ports:
      - 8078:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/html/
    links:
      - php
  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/html/
      - ./var/log/php:/var/log/
